#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function __mkdir_config {

    for file in "$source_dir"/*
    do
    filename=$(basename $file)
    if [ ! -f "$target_dir/$filename" ]
    then
        cp "$file" "$target_dir"
        echo "创建 $filename 配置文件"
    else
        echo "$filename 配置已存在，跳过创建"
    fi
    done

}

source_dir=/i
target_dir=/app/web/i
__mkdir_config

if [ ! -f "/app/web/i/.htaccess" ]
then
    cp /i/.htaccess /app/web/i/.htaccess
    echo "创建 .htaccess 配置文件"
else
    echo ".htaccess 配置已存在，跳过创建"
fi

source_dir=/config
target_dir=/app/web/config
__mkdir_config

if [ -f "/app/web/config/install.lock" ]; then
    if [ -d "/app/web/install" ]; then
        rm -rf /app/web/install
    fi
fi

if [ ! -d "/app/web/application" ]; then
    ln -sf /app/web/app /app/web/application
    echo "Soft link /app/web/app --> /app/web/application"
fi