FROM devcto/nginx-php:8.0

COPY ./html /data/wwwroot
COPY start.sh /app
RUN chown -R www:www /data/wwwroot & \
apt update
RUN rm -rf /app/entrypoint.sh & rm -rf /usr/local/php/etc/php.ini
COPY php.ini /usr/local/php/etc/
COPY entrypoint.sh /app
RUN apt-get install -y tofrodos wget & \
fromdos /start.sh & \
fromdos entrypoint.sh & \
apt remove -y tofrodos
RUN chmod +x /app/entrypoint.sh && \
chmod +x /app/start.sh
RUN apt-get install -y  wget